env:
  REGISTRY_NAME: frontend:latest
  NAMESPACE: default
  APP_NAME: angular
  SOURCE_FOLDER: ./

# This is a basic workflow to help you get started with Actions

name: Angular Kubernetes Deployment

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the dev-deployment branch
  push:
    branches: [deployment]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          check-latest: true

      - name: Install Angular
        run: |-
          npm install -g @angular/cli
          npm install -g yarn
          yarn

      - name: Build Angular
        working-directory: ./
        run: npm run build

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}

